version: '3.7'
services:
  postgres:
    image: postgres:11
    container_name: postgres
    expose:
      - 5432
#    ports:
#      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./volumes/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volumes/postgres.conf:/etc/postgres.conf
    env_file:
      - ./env/postgres.env
    environment:
      POSTGRES_MULTIPLE_DATABASES: shard0, shard1, shard2
    command: 'postgres -c config_file=/etc/postgres.conf'
  sharding:
    image: maxqfz/sharding:latest
    container_name: sharding
    ports:
      - 8080:8080
    restart: unless-stopped
    env_file:
      - ./env/sharding.env
    environment:
      JAVA_OPTS: "-XX:MaxRAMPercentage=70"
      SPRING_PROFILES_ACTIVE: "sharding"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 250M